### ISSUE TITLE
你这个blog app也是静态博客吗？

### ISSUE THREAD

**Issue by luckypoem** [airtrack/blog#1]
具体在linux vps里如何生成呢？可在https://github.com/airtrack/blog里写一篇如何操作的详细的readme吗？

**Comment by airtrack** [comment]
嗯，静态的，只自动把 `markdown` 文件生成 post，没有其它动态特性。
依赖 Python 的 `Flask` `tornado` `mobile.sniffer` `markdown` 等库，运行的话就是 `Python server.py`

**Comment by luckypoem** [comment]
hi.

root@AR:~/airtrack-blog# python server.py
Traceback (most recent call last):
  File "server.py", line 9, in <module>
    http_server.listen(80)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 196, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@AR:~/airtrack-blog#

如何修改它监听的端口号80为别的端口号？

**Comment by airtrack** [comment]
> root@AR:~/airtrack-blog# python server.py
> Traceback (most recent call last):
> File "server.py", line 9, in 
> http_server.listen(80)

报错已经提示出来。

**Comment by luckypoem** [comment]
hi.
如何分页(paginate)呢？

**Comment by airtrack** [comment]
没有分页，我这个不算一个 `Blog App` 啦，只是几行代码，刚刚满足我自己需求啦。

**Comment by luckypoem** [comment]
你这个blog app其实还不错，简单高效，要是能添加分页功能，就绝对不比jekyll差。所以你要是有空的话，还是搞搞吧。期待你搞定的那一天早日到来！
